spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3307/productdb
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:9081
        enable.idempotence: true

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#Resilience4j implementation
resilience4j:
  circuitbreaker:
    instances:
      userServices:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
  retry:
    instances:
      userServices:
        maxAttempts: 5
        waitDuration: 2s
  ratelimiter:
    instances:
      userServices:
        timeoutDuration: 0
        limitRefreshPeriod: 4s
        limitForPeriod: 2

#Actuator implementation
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true