spring:
  application:
    name: product-service

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Resilience4j implementation
resilience4j:
  circuitbreaker:
    instances:
      userServices:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
  retry:
    instances:
      userServices:
        maxAttempts: 5
        waitDuration: 2s

#Actuator implementation
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
